export const data = [
	{
		id: 1,
		img: '/imagenes/imagen1.jpg',
		nameProduct: 'Don Julio - Blanco',
		quantity: 1,
	},
	{
		id: 2,
		img: '/imagenes/imagen2.jpg',
		nameProduct: 'Don Julio 70 - Añejo',
		quantity: 1,
	},
	{
		id: 3,
		img: '/imagenes/imagen3.jpg',
		nameProduct: '1800 - Añejo',
		quantity: 1,
	},
	{
		id: 4,
		img: '/imagenes/imagen4.jpg',
		nameProduct: '1800 - Reposado',
		quantity: 1,
	},
	{
		id: 5,
		img: '/imagenes/imagen5.jpg',
		nameProduct: '30-30 - Blanco',
		quantity: 1,
	},
	{
		id: 6,
		img: '/imagenes/imagen6.jpg',
		nameProduct: '30-30 - Reposado',
		quantity: 1,
	},
	{
		id: 7,
		img: '/imagenes/imagen7.jpg',
		nameProduct: 'Maestro Dobel - Diamante',
		quantity: 1,
	},
	{
		id: 8,
		img: '/imagenes/imagen8.jpg',
		nameProduct: 'Don Julio 70 - Añejo',
		quantity: 1,
	},
	{
		id: 9,
		img: '/imagenes/imagen9.jpg',
		nameProduct: 'Tequila 1800 - Añejo',
		quantity: 1,
	},
	{
		id: 10,
		img: '/imagenes/imagen10.jpg',
		nameProduct: 'Tequila 1800',
		quantity: 1,
	},
	{
		id: 11,
		img: '/imagenes/imagen11.jpg',
		nameProduct: 'Tequila 30-30 - Blanco',
		quantity: 1,
	},
	{
		id: 12,
		img: '/imagenes/imagen12.jpg',
		nameProduct: 'Tequila 30-30 - Reposado',
		quantity: 1,
	},
	{
		id: 1,
		img: '/imagenes/imagen13.jpg',
		nameProduct: 'Don Julio - Blanco',
		quantity: 1,
	},
	{
		id: 2,
		img: '/imagenes/imagen14.jpg',
		nameProduct: 'Don Julio 70 - Añejo',
		quantity: 1,
	},
	{
		id: 3,
		img: '/imagenes/imagen15.jpg',
		nameProduct: '1800 - Añejo',
		quantity: 1,
	},
	{
		id: 4,
		img: '/imagenes/imagen16.jpg',
		nameProduct: '1800 - Reposado',
		quantity: 1,
	},
	{
		id: 5,
		img: '/imagenes/imagen17.jpg',
		nameProduct: '30-30 - Blanco',
		quantity: 1,
	},
	{
		id: 6,
		img: '/imagenes/imagen18.jpg',
		nameProduct: '30-30 - Reposado',
		quantity: 1,
	},
	{
		id: 7,
		img: '/imagenes/imagen19.jpg',
		nameProduct: 'Maestro Dobel - Diamante',
		quantity: 1,
	},
	{
		id: 8,
		img: '/imagenes/imagen20.jpg',
		nameProduct: 'Don Julio 70 - Añejo',
		quantity: 1,
	},
	{
		id: 9,
		img: '/imagenes/imagen21.jpg',
		nameProduct: 'Tequila 1800 - Añejo',
		quantity: 1,
	},
	{
		id: 10,
		img: '/imagenes/imagen22.jpg',
		nameProduct: 'Tequila 1800',
		quantity: 1,
	},
	{
		id: 11,
		img: '/imagenes/imagen23.jpg',
		nameProduct: 'Tequila 30-30 - Blanco',
		quantity: 1,
	},
	{
		id: 12,
		img: '/imagenes/imagen24.jpg',
		nameProduct: 'Tequila 30-30 - Reposado',
		quantity: 1,
	},
	{
		id: 1,
		img: '/imagenes/imagen25.jpg',
		nameProduct: 'Don Julio - Blanco',
		quantity: 1,
	},
	{
		id: 2,
		img: '/imagenes/imagen26.jpg',
		nameProduct: 'Don Julio 70 - Añejo',
		quantity: 1,
	},
	{
		id: 3,
		img: '/imagenes/imagen27.jpg',
		nameProduct: '1800 - Añejo',
		quantity: 1,
	},
	{
		id: 4,
		img: '/imagenes/imagen28.jpg',
		nameProduct: '1800 - Reposado',
		quantity: 1,
	},
	{
		id: 5,
		img: '/imagenes/imagen29.jpg',
		nameProduct: '30-30 - Blanco',
		quantity: 1,
	},
	{
		id: 6,
		img: '/imagenes/imagen30.jpg',
		nameProduct: '30-30 - Reposado',
		quantity: 1,
	},
	{
		id: 7,
		img: '/imagenes/imagen31.png',
		nameProduct: 'Maestro Dobel - Diamante',
		quantity: 1,
	},
	{
		id: 8,
		img: '/imagenes/imagen32.jpg',
		nameProduct: 'Don Julio 70 - Añejo',
		quantity: 1,
	},
	{
		id: 9,
		img: '/imagenes/imagen33.png',
		nameProduct: 'Tequila 1800 - Añejo',
		quantity: 1,
	},
	{
		id: 10,
		img: '/imagenes/imagen34.jpg',
		nameProduct: 'Tequila 1800',
		quantity: 1,
	},
	{
		id: 11,
		img: '/imagenes/imagen35.jpg',
		nameProduct: 'Tequila 30-30 - Blanco',
		quantity: 1,
	},
	{
		id: 12,
		img: '/imagenes/imagen36.jpg',
		nameProduct: 'Tequila 30-30 - Reposado',
		quantity: 1,
	},
	{
		id: 11,
		img: '/imagenes/imagen37.jpg',
		nameProduct: 'Tequila 30-30 - Blanco',
		quantity: 1,
	},
	{
		id: 12,
		img: '/imagenes/imagen38.jpg',
		nameProduct: 'Tequila 30-30 - Reposado',
		quantity: 1,
	},
];
