// data.js
export const data = [

    //Modificar los nombres de los productos

    // Licores
    { "id": 1, "img": "/imagenes/licores/D70.jpg", nameProduct: "Don Julio 70", quantity: 1, category: "Licores" },
    { "id": 2, "img": "/imagenes/licores/D70Blanco.jpg", nameProduct: "Don Julio 70 Blanco", quantity: 1, category: "Licores" },
    { "id": 3, "img": "/imagenes/licores/7LBlanco.jpg", nameProduct: "7 Leguas Blanco", quantity: 1, category: "Licores" },
    { "id": 4, "img": "/imagenes/licores/1800Añejo.jpg", nameProduct: "1800 Añejo", quantity: 1, category: "Licores" },
    { "id": 5, "img": "/imagenes/licores/1800Blanco.jpg", nameProduct: "1800 Blanco", quantity: 1, category: "Licores" },
    { "id": 6, "img": "/imagenes/licores/1800Reposado.jpg", nameProduct: "1800 Reposado", quantity: 1, category: "Licores" },
    { "id": 7, "img": "/imagenes/licores/1800Cristalino.jpg", nameProduct: "1800 Cristalino", quantity: 1, category: "Licores" },
    { "id": 8, "img": "/imagenes/licores/3030Blanco.jpg", nameProduct: "30-30 Blanco", quantity: 1, category: "Licores" },
    { "id": 9, "img": "/imagenes/licores/3030Reposado.jpg", nameProduct: "30-30 Reposado", quantity: 1, category: "Licores" },
    { "id": 10, "img": "/imagenes/licores/plata.jpg", nameProduct: "Centenario Plata", quantity: 1, category: "Licores" },
    { "id": 11, "img": "/imagenes/licores/Añejo.jpg", nameProduct: "Centenario Añejo", quantity: 1, category: "Licores" },
    { "id": 12, "img": "/imagenes/licores/Baileys.jpg", nameProduct: "Baileys", quantity: 1, category: "Licores" },
    { "id": 13, "img": "/imagenes/licores/Barullo.jpg", nameProduct: "Barullo", quantity: 1, category: "Licores" },
    { "id": 14, "img": "/imagenes/licores/BuchanansD.jpg", nameProduct: "Buchanan's Deluxe", quantity: 1, category: "Licores" },
    { "id": 15, "img": "/imagenes/licores/CabritoReposado.jpg", nameProduct: "Cabrito Reposado", quantity: 1, category: "Licores" },
    { "id": 16, "img": "/imagenes/licores/CAClasicoReposado.jpg", nameProduct: "Centenario Clásico Reposado", quantity: 1, category: "Licores" },
    { "id": 17, "img": "/imagenes/licores/caribeMandarina.jpg", nameProduct: "Caribe Mandarina", quantity: 1, category: "Licores" },
    { "id": 18, "img": "/imagenes/licores/caribeMKiwi.jpg", nameProduct: "Caribe Mango Kiwi", quantity: 1, category: "Licores" },
    { "id": 19, "img": "/imagenes/licores/caribeTinto.jpg", nameProduct: "Caribe Tinto", quantity: 1, category: "Licores" },
    { "id": 20, "img": "/imagenes/licores/caribeUltra.jpg", nameProduct: "Caribe Ultra", quantity: 1, category: "Licores" },
    { "id": 21, "img": "/imagenes/licores/RedLabel.jpg", nameProduct: "Red Label", quantity: 1, category: "Licores" },
    { "id": 22, "img": "/imagenes/licores/Hennessy.jpg", nameProduct: "Hennessy", quantity: 1, category: "Licores" },
    { "id": 23, "img": "/imagenes/licores/HPlata.jpg", nameProduct: "Herradura Plata", quantity: 1, category: "Licores" },
    { "id": 24, "img": "/imagenes/licores/HReposado.jpg", nameProduct: "Herradura Reposado", quantity: 1, category: "Licores" },
    { "id": 25, "img": "/imagenes/licores/HUltra.jpg", nameProduct: "Herradura Ultra", quantity: 1, category: "Licores" },
    { "id": 26, "img": "/imagenes/licores/MDDiamante.jpg", nameProduct: "Maestro Dobel Diamante", quantity: 1, category: "Licores" },
    { "id": 27, "img": "/imagenes/licores/NMCantrito350ml.jpg", nameProduct: "Nuevo Mundo Cantinito 350ml", quantity: 1, category: "Licores" },
    { "id": 28, "img": "/imagenes/licores/PVAñejo.jpg", nameProduct: "Patrón Añejo", quantity: 1, category: "Licores" },
    { "id": 29, "img": "/imagenes/licores/PVBlanco.jpg", nameProduct: "Patrón Blanco", quantity: 1, category: "Licores" },
    { "id": 30, "img": "/imagenes/licores/PVReposado.jpg", nameProduct: "Patrón Reposado", quantity: 1, category: "Licores" },
    { "id": 31, "img": "/imagenes/licores/SKYYArandano.jpg", nameProduct: "SKYY Arándano", quantity: 1, category: "Licores" },
    { "id": 32, "img": "/imagenes/licores/SKYMDurazno.jpg", nameProduct: "SKYY Durazno", quantity: 1, category: "Licores" },
    { "id": 33, "img": "/imagenes/licores/VodkaAbsolut.jpg", nameProduct: "Vodka Absolut", quantity: 1, category: "Licores" },
    { "id": 34, "img": "/imagenes/licores/VodkaOsoNegro.jpg", nameProduct: "Vodka Oso Negro", quantity: 1, category: "Licores" },



    { "id": 35, "img": "/imagenes/cervezas/CExtra355.jpg", nameProduc: "Corona Extra 355ml", quantity: 1, category: "Cervezas" },
    { "id": 36, "img": "/imagenes/cervezas/CExtra473.jpg", nameProduc: "Corona Extra 473ml", quantity: 1, category: "Cervezas" },
    { "id": 37, "img": "/imagenes/cervezas/CFamiliar.jpg", nameProduc: "Corona Familiar", quantity: 1, category: "Cervezas" },
    { "id": 38, "img": "/imagenes/cervezas/CLight330.jpg", nameProduc: "Corona Light 330ml", quantity: 1, category: "Cervezas" },
    { "id": 39, "img": "/imagenes/cervezas/CLight355.jpg", nameProduc: "Corona Light 355ml", quantity: 1, category: "Cervezas" },
    { "id": 40, "img": "/imagenes/cervezas/CMega.jpg", nameProduc: "Corona Mega", quantity: 1, category: "Cervezas" },
    { "id": 41, "img": "/imagenes/cervezas/CModeloNegra.jpg", nameProduc: "Corona Modelo Negra", quantity: 1, category: "Cervezas" },
    { "id": 42, "img": "/imagenes/cervezas/Coronita.jpg", nameProduc: "Coronita", quantity: 1, category: "Cervezas" },
    { "id": 43, "img": "/imagenes/cervezas/CPacifico.jpg", nameProduc: "Cerveza Pacífico", quantity: 1, category: "Cervezas" },
    { "id": 44, "img": "/imagenes/cervezas/CTradicional473.jpg", nameProduc: "Corona Tradicional 473ml", quantity: 1, category: "Cervezas" },
    { "id": 45, "img": "/imagenes/cervezas/MEspecial.jpg", nameProduc: "Modelo Especial", quantity: 1, category: "Cervezas" },
    { "id": 46, "img": "/imagenes/cervezas/MEspecialCerveza.jpg", nameProduc: "Modelo Especial Cerveza", quantity: 1, category: "Cervezas" },
    { "id": 47, "img": "/imagenes/cervezas/SolClamato.jpg", nameProduc: "Sol Clamato", quantity: 1, category: "Cervezas" },
    { "id": 48, "img": "/imagenes/cervezas/Victoria.jpg", nameProduc: "Cerveza Victoria", quantity: 1, category: "Cervezas" },
    { "id": 49, "img": "/imagenes/cervezas/victoriaL.jpg", nameProduc: "Victoria Lata", quantity: 1, category: "Cervezas" },
    { "id": 50, "img": "/imagenes/cervezas/Barillito.jpg", nameProduc: "Barillito", quantity: 1, category: "Cervezas" },


    // Bebidas
    { id: 51, img: '/imagenes/bebidas/7Up.jpg', nameProduct: '7 Up', quantity: 1, category: 'Bebidas' },
    { id: 52, img: '/imagenes/bebidas/Amper.jpg', nameProduct: 'Amper', quantity: 1, category: 'Bebidas' },
    { id: 53, img: '/imagenes/bebidas/AmperBlueberry.jpg', nameProduct: 'Amper Blueberry', quantity: 1, category: 'Bebidas' },
    { id: 54, img: '/imagenes/bebidas/Coca.jpg', nameProduct: 'Coca Cola', quantity: 1, category: 'Bebidas' },
    { id: 55, img: '/imagenes/bebidas/Coca2,5L.jpg', nameProduct: 'Coca Cola 2.5L', quantity: 1, category: 'Bebidas' },
    { id: 56, img: '/imagenes/bebidas/ElectrolitCoco.jpg', nameProduct: 'Electrolit Coco', quantity: 1, category: 'Bebidas' },
    { id: 57, img: '/imagenes/bebidas/ElectrolitFresa.jpg', nameProduct: 'Electrolit Fresa', quantity: 1, category: 'Bebidas' },
    { id: 58, img: '/imagenes/bebidas/Peñafiel2L.jpg', nameProduct: 'Peñafiel 2L', quantity: 1, category: 'Bebidas' },
    { id: 59, img: '/imagenes/bebidas/Peñafiel600ml.jpg', nameProduct: 'Peñafiel 600ml', quantity: 1, category: 'Bebidas' },
    { id: 60, img: '/imagenes/bebidas/PeñafielTwist.jpg', nameProduct: 'Peñafiel Twist', quantity: 1, category: 'Bebidas' },
    { id: 61, img: '/imagenes/bebidas/Squirt.jpg', nameProduct: 'Squirt', quantity: 1, category: 'Bebidas' },
    { id: 62, img: '/imagenes/bebidas/Squirt600ml.jpg', nameProduct: 'Squirt 600ml', quantity: 1, category: 'Bebidas' },

    // Botanas
    { id: 63, img: '/imagenes/botana/KACANGEnchilado.jpg', nameProduct: 'Kacang Enchilado', quantity: 1, category: 'Botanas' },
    { id: 64, img: '/imagenes/botana/KacangSalYLimon.jpg', nameProduct: 'Kacang Sal y Limón', quantity: 1, category: 'Botanas' },
    { id: 65, img: '/imagenes/botana/KARATEJapones.jpg', nameProduct: 'Karate Japonés', quantity: 1, category: 'Botanas' },
    { id: 66, img: '/imagenes/botana/paquetaxoF.jpg', nameProduct: 'Paquetaxo Fiesta', quantity: 1, category: 'Botanas' },
    { id: 67, img: '/imagenes/botana/PaquetaxoBotanero.jpg', nameProduct: 'Paquetaxo Botanero', quantity: 1, category: 'Botanas' },
    { id: 68, img: '/imagenes/botana/PaquetaxoM.jpg', nameProduct: 'Paquetaxo Mix', quantity: 1, category: 'Botanas' },
    { id: 69, img: '/imagenes/botana/Rancheritos.jpg', nameProduct: 'Rancheritos', quantity: 1, category: 'Botanas' },
    { id: 70, img: '/imagenes/botana/RufflesQueso.jpg', nameProduct: 'Ruffles Queso', quantity: 1, category: 'Botanas' },
    { id: 71, img: '/imagenes/botana/Sabritas.jpg', nameProduct: 'Sabritas', quantity: 1, category: 'Botanas' },
    { id: 72, img: '/imagenes/botana/TostitosFHot.jpg', nameProduct: 'Tostitos Flaming Hot', quantity: 1, category: 'Botanas' },
    { id: 73, img: '/imagenes/botana/TotitosVerdes.jpg', nameProduct: 'Totitos Verdes', quantity: 1, category: 'Botanas' },

    // Extras
    { id: 57, img: '/imagenes/extras/Clamato.jpg', nameProduct: 'Clamato', quantity: 1, category: 'Extras' },
    { id: 58, img: '/imagenes/extras/Hielo5kg.jpg', nameProduct: 'Hielo 5kg', quantity: 1, category: 'Extras' },
    { id: 59, img: '/imagenes/extras/MalboroGold.jpg', nameProduct: 'Malboro Gold', quantity: 1, category: 'Extras' },
    { id: 60, img: '/imagenes/extras/MalboroRojo.jpg', nameProduct: 'Malboro Rojo', quantity: 1, category: 'Extras' },
    { id: 61, img: '/imagenes/extras/PallMallAlaska.jpg', nameProduct: 'Pall Mall Alaska', quantity: 1, category: 'Extras' },
    { id: 62, img: '/imagenes/extras/PallMallClassics.jpg', nameProduct: 'Pall Mall Classics', quantity: 1, category: 'Extras' },
    { id: 63, img: '/imagenes/extras/PallMallLondon.jpg', nameProduct: 'Pall Mall London', quantity: 1, category: 'Extras' },
    { id: 64, img: '/imagenes/extras/PallMallMykonos.jpg', nameProduct: 'Pall Mall Mykonos', quantity: 1, category: 'Extras' },
    { id: 65, img: '/imagenes/extras/PallMallTokyo.jpg', nameProduct: 'Pall Mall Tokyo', quantity: 1, category: 'Extras' },
    { id: 66, img: '/imagenes/extras/Shots14.jpg', nameProduct: 'Shots 14', quantity: 1, category: 'Extras' },
];
